import type { Automation, Run } from "../types.ts";

export interface Detection {
  ok: boolean;
  binary: string | null;
  version: string | null;
  loggedIn: boolean | null; // null = unknown
  note?: string;
}

export interface ModelInfo { id: string; label: string; free: boolean; note?: string }

export interface BuiltCommand {
  argv: string[];
  env: Record<string, string>;
  cwd: string;
  stdin?: string; // prompt text piped on stdin
}

export interface ParsedResult {
  ok: boolean;
  sessionId?: string;
  error?: string;
  rateLimited?: { retryAt?: Date; message: string };
  result?: unknown;
  summary?: string;
}

export interface BuildContext {
  runDir: string;           // ~/.autoed/runs/<id>
  promptPath: string;       // rendered prompt on disk
  resumeSessionId: string | null;
  warn: (msg: string) => void;
}

export interface Backend {
  id: "claude" | "devin";
  label: string;
  defaultModel: string;
  agentModes: Array<{ id: string; label: string; dangerous?: boolean }>;
  defaultAgentMode: string;
  detect(): Promise<Detection>;
  listModels(): Promise<ModelInfo[]>;
  /** Session id pre-generated by autoed when the backend allows it (Claude). */
  newSessionId(): string | null;
  buildCommand(run: Run, automation: Automation, prompt: string, ctx: BuildContext): Promise<BuiltCommand>;
  parseResult(run: Run, stdout: string, stderr: string, exitCode: number | null, ctx: BuildContext): Promise<ParsedResult>;
  openInDesktop(run: Run): Promise<void>;
}
